### ISSUE TITLE
Different API response depending on platform (NXOS/ACI vs IOS/IOS-XE)

### ISSUE THREAD

**Issue by NWMichl** [CiscoPSIRT/openVulnAPI#83]
**Describe the bug**
First fixed software versions are reported with a different data structure and naming depending on whether NXOS/ACI or IOS(XE) is used for the API query.

**To Reproduce**
An API query with NXOS 7.0(3)I7(8) results in

```
(...)
platforms:
- firstFixes:
  - id: '279749'
    name: 7.0(3)I7(9)
  id: '265096'
  name: Cisco Nexus 9000 Series Switches
  vulnerabilityState: vulnerable
(...) 
```

But an API query with IOSXE 03.16.09.S results in 

```
(...)
firstFixed:
- 3.18.2S
(...) 
```

**Expected behavior**
Since the NXOS/ACI variant allows more extensive parameters already, an adaptation of the IOS response would be desirable.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
BTW: The API itself is worth gold and makes our work a lot easier, so I would like to thank you for your work!
But such inconsistencies should be avoided, right?
